apiVersion: batch/v1
kind: Job
metadata:
  name: one-off-migration
  labels:
    app: go-demo-app
    component: migration
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migrate
        image: busybox:1.36
        command: ["sh","-c","echo running db migration && sleep 5 && echo ok"]
