apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-app-liveness
  labels:
    app: go-demo-app
    component: liveness
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-demo-app
      component: liveness
  template:
    metadata:
      labels:
        app: go-demo-app
        component: liveness
    spec:
      containers:
      - name: app
        image: nginx:1.27.0
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /live
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
