apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-app-resources
  labels:
    app: go-demo-app
    component: resources
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-demo-app
      component: resources
  template:
    metadata:
      labels:
        app: go-demo-app
        component: resources
    spec:
      containers:
      - name: app
        image: nginx:1.27.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
