apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  DB_URL: ZGJwb3N0Z3Jlc3FsOi8vdXNlcjpzZWNyZXRAZGItc2VydmljZToyNTQzL2FwcA==  # base64("dbpostgresql://user:secret@db-service:2543/app")
  API_KEY: QUlBLVNBUExFQVBJS0VZLURPTk9UUSE=                                # base64("AIA-SAMPLEAPIKEY-DONOT!")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-app-secret
  labels:
    app: go-demo-app
    component: secret-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-demo-app
      component: secret-env
  template:
    metadata:
      labels:
        app: go-demo-app
        component: secret-env
    spec:
      containers:
      - name: app
        image: nginx:1.27.0
        envFrom:
        - secretRef:
            name: app-secret
        ports:
        - containerPort: 8080
