apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-app-readiness
  labels:
    app: go-demo-app
    component: readiness
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-demo-app
      component: readiness
  template:
    metadata:
      labels:
        app: go-demo-app
        component: readiness
    spec:
      containers:
      - name: app
        image: nginx:1.27.0
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
